export { default as HeroSection } from './HeroSection'
export { default as AboutSection } from './AboutSection'
export { default as ServicesSection } from './ServicesSection'
export { default as PortfolioSection } from './PortfolioSection'
export { default as CtaSection } from './CtaSection'
